# Generated by Django 5.0.1 on 2024-02-23 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
